"""add users

Revision ID: df989ff96517
Revises: 
Create Date: 2026-07-29 07:52:31.851817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df989ff96517'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bounties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('reward_usd', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('skills', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_deadline'), 'bounties', ['deadline'], unique=False)
    op.create_index(op.f('ix_bounties_id'), 'bounties', ['id'], unique=False)
    op.create_index(op.f('ix_bounties_owner_id'), 'bounties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_bounties_platform'), 'bounties', ['platform'], unique=False)
    op.create_index(op.f('ix_bounties_reward_usd'), 'bounties', ['reward_usd'], unique=False)
    op.create_index(op.f('ix_bounties_status'), 'bounties', ['status'], unique=False)
    op.create_index(op.f('ix_bounties_title'), 'bounties', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bounties_title'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_status'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_reward_usd'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_platform'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_owner_id'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_id'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_deadline'), table_name='bounties')
    op.drop_table('bounties')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
